name: Bi-directional Wiki Sync Action

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:
    
env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SYNC }}
          ref: master
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@master
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.SYNC }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          # gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: master # since default branch is develop in this example
          uses: newrelic/wiki-sync-action@v1.0.0
  
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@master
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.SYNC }}
